version: '3.8'

services:
  database:
    image: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: rootpw
      MYSQL_DATABASE: task
    volumes:
      - task-db:/var/lib/mysql
    ports:
      - 3306:3306
  
  task:
    build:
      context: ./task
      target: runner
    environment:
      APP_ENV: dev
    volumes:
      - ./task:/app
      - /app/node_modules
    ports:
      - 5000:5000
    stdin_open: true

  dev:
    image: node:18-slim
    working_dir: /app
    volumes:
      - ./5iw3-ms-task:/app
      - /app/node_modules

volumes:
  task-db: